baseURL = "http://example.org/"
languageCode = "en-us"
title = "Colin Gerritsen"
theme = "hallo"
[Author]
    name = "Colin"

[params]
    [[params.links]]
        icon = "linkedin"
        title = "Linkedin"
        url = "https://www.linkedin.com/in/colin-gerritsen-7821aa148"
 
    [params.colors]
        background = "#1A1A1A"
        foreground = "#FFFFFF"
        hover = "#1597A7"